### ISSUE TITLE
Video Player: Switching from Previous Frame to Next Frame changes time by 1ms

### ISSUE THREAD

**Issue by JStratil** [oaubert/advene#7] opened 2017-02-07 16:29 UTC
When using the Video Player going to previous frame and then back to next frame the time changes by 1ms. By changing back and forth between previous and next frame the player time actually moves  backwards in time. Is it on purpose or an irregularity?

**Comment by oaubert** [comment] 2017-02-09 18:36
I cannot reproduce this behaviour on my Linux computer, with different video formats. It may be caused by specific videos, specific video formats or even OS specificities.

**Comment by oaubert** [comment] 2017-04-28 14:34
Fixed in the latest version (probably a gstreamer 0.10 related issue)

**Closed by oaubert** 2017-04-28 14:34 UTC
