### ISSUE TITLE
Screenshot Discrepancy

### ISSUE THREAD

**Issue by AdaTsche** [oaubert/advene#8] opened 2017-02-09 17:57 UTC
In the note taking editor advene uses sometimes a different screenshot for the timemarker than the main videoplayer shows. This becomes apparent when creating a timemarker at the end of a shot. The main videoplayer shows the first image of the next shot while the time-marker-screen-shot shows the last frame from the previous shot. Probably it is just a visual discrepancy and not relevant for the underlying timecode.

**Comment by oaubert** [comment] 2017-06-27 10:21
Duplicate of #15

**Closed by oaubert** 2017-06-27 10:21 UTC
